#pip_install_packages:
#      - name: proxmoxer
#      - name: requests
#      - name: paramiko

ansible_user: "root"
ansible_become_pass: "{{ lookup('keepass', 'pveroot', 'password') }}"


cloud_init_packages:
  #- qemu-kvm
  #- qemu-utils
  - genisoimage
  - virtinst
