---
  #- hosts: proxmox
  - import_playbook: ./initial/cloudinit_setup.yml
  - import_playbook: ./bootstrapper/bootstrap_pihole.yml
  #- import_playbook: ./programms/pihole.yml
  - import_playbook: ./programms/tmux.yml
  - import_playbook: ./initial/install_programs.yml
