#cloud-config
manage_etc_hosts: true
password: "$6$1AK708sSWZMaCFQX$dmxdl/H59x7M.VfDFHlTA8sONA/TuEi65pChWDmf7LgYs4o73t0WVD38JSgZaxfdDEG84xFghR9jWiwlhhIzT1"
ssh_authorized_keys:
  -ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCodE/I8vLzHxc8JNJnjTY4dbi/GG62wifbuWykZg94XGdUUOJTt81/SjWDqccjcdQDNs/LZn1KHuioUVyG4G/kgjS08xut99FzqOLT96jRuoh9wKYhIXbQcaqJK4w0P4FxZZ6ewlu4lsq8gLK5nzwYci0ylTqqX14XafI5mBdqCUXe9Sk6Hxhpim3aWzKSgwGdpwoDBIOg0G0RWrkDvZa1+EUg5W29DB6A1+DEJGSf7X9wEomGzI2Hry2BsbbthwTB//HA8vxHlCoXXF/ljXASdT/J/R1Qk6cBsfIEYmBtrmV9nHvmrWlQFGaq0QhvFKntEYmCHF9ul1HMtBgu9ylcb+woVPRQvuVXE3TdPCSvw5edALQAne40ly4o2GZLG3TPYBNGW2YW65OW7ljFkQGpgGZBSB9KL4TbHoUo3NQ8aY1rnmm5y2qZFQ109C9yXsiSt/mLqdAa+GhvQ8jEg88Xzl9O1sPaqq6PTBH/muHs65TtF2dPCgQi+v551Ncdvd0XWyiWl9wCyQ/t5qpSWoS32HW8Tnpf0kaKnAm7Xg9d8o3sqjKUHRbx1WFLSiINLXg3ansLaxGieUnWSayRbWn4UXQiM6Q70cmXdkYpal4g/pyVux04evB16ZbhGTnoGYczDaOruRgo6rnQbLNxa4aNWvIkfg/t3JE8YEd7SyZlCw== user@user-VirtualBox
chpasswd:
  expire: False
users:
  - default
package_upgrade: true
