---
- name: restart cloud-init-local.service
  service:
    name: cloud-init-local.service
    enabled: true
    state: restarted
  become: true

- name: Gather all facts of cloud init for prove
  community.general.cloud_init_data_facts:
  register: result

- ansible.builtin.debug:
    var: result
