---
# tasks file for ansible-cloud-init
- include_tasks: install.yml

- include_tasks: config.yml

- include_tasks: clean.yml

- include_tasks: service.yml

- include_tasks: prepair_vm_img.yml

- include_tasks: create_vm.yml
