

# Source: https://github.com/fheinle/ansible-pihole/blob/master/defaults/main.yml
user_pihole: "pihole"
group_pihole: "pihole"

web_password: $6$hHWBwSsgxXnwX$pG2YIHf9k4trQ7ak27LcF6CLXF45QLXyENOZBAApCnae/fDvzMNO0FM4fV9fDXgKHlAOY5CN2725DyolZnhEY.
ipv4_address: 192.168.178.15
git_repo_web_interface: "https://github.com/pi-hole/AdminLTE.git"
git_repo_core: "https://github.com/fheinle/pi-hole.git"
fspath_web_interface: "/var/www/admin"
fspath_web_directory: "/var/www/pihole"
fspath_pihole: "/opt/pihole"
fspath_pihole_src: "/etc/.pihole"
fspath_pihole_config: "/etc/pihole"

network_interface: eth0
dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
