---
  - name: install cloud init
    ansible.builtin.apt:
      name: cloud-init
      state: present

  - name: setup cloudinit.cfg
    become: true
    ansible.builtin.template:
      src: "cloud.cfg"
      dest: "/etc/cloud/cloud.cfg"
