---
  users_tmux:
    - username: user
      tmux_allow: false
      tmux_downloadpath: ""
      tmux_conf_destination: "/home/user/.tmux.conf"
      tmux_bashrc_destination: "/home/user/.bashrc"
      tmux_standardsession_name: "default"
    - username: root
      tmux_allow: true
      tmux_downloadpath: ""
      tmux_conf_destination: "/root/.tmux.conf"
      tmux_bashrc_destination: "/root/.bashrc"
      tmux_standardsession_name: "default"
