---
  - name: Clone VM
    community.general.proxmox_kvm:
      api_user: root@pam
      api_password: "{{ lookup('keepass', 'pveroot', 'password') }}"
      api_host: pve
      clone: testvm-template
      name: testvm-clone
      node: pve
      storage: local-lvm
      format: raw
      timeout: 500
      net:
        net0: "virtio,bridge=vmbr0"
      ipconfig:
        ipconfig0: "ip=192.168.56.201/24"
